# Generated by Django 4.2.11 on 2024-09-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fisioterapist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialty', models.CharField(choices=[('ORTHO', 'Ortopedista'), ('NEURO', 'Neurológica'), ('CARDIO', 'Cardiopulmonar'), ('PEDIAT', 'Pediátrica'), ('GERIAT', 'Geriátrica'), ('SPORT', 'Desportiva'), ('OTHER', 'Outros')], max_length=18)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
