# Generated by Django 4.2.11 on 2024-09-01 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fisiologista', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisioterapist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_tratamento', models.CharField(choices=[('ORTHO', 'Ortopedista'), ('NEURO', 'Neurológica'), ('CARDIO', 'Cardiopulmonar'), ('PEDIAT', 'Pediátrica'), ('GERIAT', 'Geriátrica'), ('SPORT', 'Desportiva'), ('OTHER', 'Outros')], max_length=255)),
                ('resumo_problemas', models.TextField(max_length=6000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiologista.fisioterapist')),
            ],
        ),
    ]
