# Generated by Django 4.2.11 on 2024-09-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisiologista', '0003_alter_fisioterapist_user_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='hora',
            new_name='time',
        ),
    ]
