# Generated by Django 4.2.11 on 2024-09-01 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisiologista', '0004_rename_hora_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='profissional',
            new_name='professional',
        ),
    ]
