# Generated by Django 4.2.11 on 2024-09-02 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisiologista', '0005_rename_profissional_appointment_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fisiologista.fisioterapist'),
        ),
    ]
