# Generated by Django 4.2.11 on 2024-09-02 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisiologista', '0006_alter_appointment_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fisiologista.fisioterapist'),
        ),
    ]
